#!/usr/bin/env python3
"""Patch Pier's mini_swe_agent.py to switch Debian apt sources from HTTP to HTTPS.

The swe-bench agent Dockerfile (generated by Pier at runtime via
``write_agent_dockerfile``) hardcodes ``apt-get update && apt-get install -y
curl build-essential git`` in ``MiniSweAgent.install_spec()``.  When the base
image's apt sources use **HTTP** (e.g. ``http://deb.debian.org/debian``) and
the environment routes through an HTTP proxy that returns ``502 Bad Gateway``
for HTTP traffic, the build fails.

This patch injects a ``sed`` command *before* ``apt-get update`` that rewrites
all known Debian apt source URLs from ``http://`` to ``https://``.  HTTPS works
through the proxy's ``CONNECT`` tunnel — the same mechanism Docker uses for
image pulls.

Usage::

    python3 scripts/patch_pier_apt.py           # auto-detect & patch
    python3 scripts/patch_pier_apt.py /path/to/mini_swe_agent.py
    python3 scripts/patch_pier_apt.py --check   # exit 0 if already patched

Idempotent: re-running on an already-patched file is a no-op.
"""

from __future__ import annotations

import ast
import sys
from pathlib import Path

MARKER = "PATCHED_APT_HTTPS"

TARGET = '"  apt-get update && apt-get install -y curl build-essential git;"'

MARKER_LINE = (
    f"            # {MARKER}: switch Debian apt HTTP->HTTPS for proxy compatibility\n"
)

SED_LINE = (
    '            "  sed -i '
    "'s|http://deb.debian.org|https://deb.debian.org|g; "
    "s|http://security.debian.org|https://security.debian.org|g; "
    "s|http://deb.nodesource.com|https://deb.nodesource.com|g' "
    "/etc/apt/sources.list /etc/apt/sources.list.d/*.list "
    '/etc/apt/sources.list.d/*.sources 2>/dev/null || true;"\n'
)


def find_module() -> Path | None:
    """Locate the installed pier mini_swe_agent module."""
    try:
        import pier.agents.installed.mini_swe_agent as mod  # type: ignore

        return Path(mod.__file__)
    except Exception:
        return None


def patch_file(path: Path) -> bool:
    """Patch *path* in-place.  Returns True on success."""
    lines = path.read_text(encoding="utf-8").splitlines(keepends=True)

    if any(MARKER in line for line in lines):
        print(f"Already patched: {path}")
        return True

    patched: list[str] = []
    inserted = False
    for line in lines:
        if not inserted and TARGET in line:
            patched.append(MARKER_LINE)
            patched.append(SED_LINE)
            patched.append(line)
            inserted = True
        else:
            patched.append(line)

    if not inserted:
        print(f"ERROR: target line not found in {path}")
        print(f"  looking for: {TARGET}")
        return False

    new_content = "".join(patched)
    try:
        ast.parse(new_content)
    except SyntaxError as exc:
        print(f"ERROR: patched file would have a syntax error: {exc}")
        return False

    path.write_text(new_content, encoding="utf-8")
    print(f"Patched: {path}")
    print(f"  Injected sed to switch Debian apt HTTP->HTTPS before apt-get update")
    return True


def main() -> int:
    check_only = "--check" in sys.argv or "--check-only" in sys.argv
    args = [a for a in sys.argv[1:] if not a.startswith("--")]

    if args:
        path = Path(args[0])
    else:
        path = find_module()
        if path is None:
            print("ERROR: cannot locate pier/agents/installed/mini_swe_agent.py")
            print("  Make sure pier is installed (pip install evalscope[deep_swe])")
            return 1

    print(f"Pier agent module: {path}")

    if check_only:
        already = MARKER in path.read_text(encoding="utf-8")
        print(f"Already patched: {already}")
        return 0 if already else 1

    return 0 if patch_file(path) else 1


if __name__ == "__main__":
    sys.exit(main())
